apiVersion: v1
kind: ReplicationController
metadata:
   name: frontend
   labels:
      name: frontend
spec:
   replicas: 3
   selector:
      name: frontend
   template:
      metadata:
         labels:
            name: frontend
      spec:
         containers:
         - name: frontend
           image: asia.gcr.io/projectname/frontend
           ports:
           - containerPort: 80
             protocol: TCP
